<?xml version="1.0" encoding="utf-8"?><Database Name="PreAccountancy" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-83SGN10\SQLEXPRESS;Initial Catalog=PreAccountancy;Integrated Security=True" SettingsObjectName="PreAccountancy.Properties.Settings" SettingsPropertyName="PreAccountancyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_Stock" Member="TBL_Stocks">
    <Type Name="TBL_Stock">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StockBarcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StockCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StockName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StockUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StockPurchasePrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StockSalePrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StockPurchaseTAX" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StockSaleTAX" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StockGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockPicture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StockSaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockSaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StockEditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_StockGroup" Member="TBL_StockGroups">
    <Type Name="TBL_StockGroup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupSaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupSaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GroupEditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CurrentGroup" Member="TBL_CurrentGroups">
    <Type Name="TBL_CurrentGroup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrentGroupName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentGroupCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentGroupSaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CurrentGroupSaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrentGroupEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CurrentGroupEditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_Current" Member="TBL_Currents">
    <Type Name="TBL_Current">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentTaxOffice" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentTaxNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CurrentGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrentCountry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentCity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentDistrict" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentAddress" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CurrentPhone1" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="CurrentPhone2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="CurrentFax1" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="CurrentFax2" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="CurrentWebAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CurrentMailInfo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CurrentAuthorized1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentAuthorized1Mail" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CurrentAuthorized2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentAuthorized2Mail" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CurrentSaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CurrentSaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrentEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CurrentEditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_Safe" Member="TBL_Safes">
    <Type Name="TBL_Safe">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SafeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SafeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SafeMovement" Member="TBL_SafeMovements">
    <Type Name="TBL_SafeMovement">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SafeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocumentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GCCode" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CurrentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Desciption" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CurrentMovement" Member="TBL_CurrentMovements">
    <Type Name="TBL_CurrentMovement">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocumentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Debt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Credit" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.VW_SAFEMOVEMENT" Member="VW_SAFEMOVEMENTs">
    <Type Name="VW_SAFEMOVEMENT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SafeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SafeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SafeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocumentNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocumentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Inflow" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Outflow" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Desciption" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.VW_SAFESTATUS" Member="VW_SAFESTATUS">
    <Type Name="VW_SAFESTATUS">
      <Column Name="SafeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Inflow" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Outflow" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_SAFELIST" Member="VW_SAFELISTs">
    <Type Name="VW_SAFELIST">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SafeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SafeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Inflow" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Outflow" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_BANKMOVEMENTS" Member="TBL_BANKMOVEMENTs">
    <Type Name="TBL_BANKMOVEMENT">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BankID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocumentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GCCode" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_BANKS" Member="TBL_BANKs">
    <Type Name="TBL_BANK">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IBAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Branch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Authorized" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AuthorizedMail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>