#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreAccountancy.Functions
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PreAccountancy")]
	public partial class DbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_Stock(TBL_Stock instance);
    partial void UpdateTBL_Stock(TBL_Stock instance);
    partial void DeleteTBL_Stock(TBL_Stock instance);
    partial void InsertTBL_StockGroup(TBL_StockGroup instance);
    partial void UpdateTBL_StockGroup(TBL_StockGroup instance);
    partial void DeleteTBL_StockGroup(TBL_StockGroup instance);
    partial void InsertTBL_CurrentGroup(TBL_CurrentGroup instance);
    partial void UpdateTBL_CurrentGroup(TBL_CurrentGroup instance);
    partial void DeleteTBL_CurrentGroup(TBL_CurrentGroup instance);
    partial void InsertTBL_Current(TBL_Current instance);
    partial void UpdateTBL_Current(TBL_Current instance);
    partial void DeleteTBL_Current(TBL_Current instance);
    #endregion
		
		public DbDataContext() : 
				base(global::PreAccountancy.Properties.Settings.Default.PreAccountancyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_Stock> TBL_Stocks
		{
			get
			{
				return this.GetTable<TBL_Stock>();
			}
		}
		
		public System.Data.Linq.Table<TBL_StockGroup> TBL_StockGroups
		{
			get
			{
				return this.GetTable<TBL_StockGroup>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CurrentGroup> TBL_CurrentGroups
		{
			get
			{
				return this.GetTable<TBL_CurrentGroup>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Current> TBL_Currents
		{
			get
			{
				return this.GetTable<TBL_Current>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Stock")]
	public partial class TBL_Stock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _StockBarcode;
		
		private string _StockCode;
		
		private string _StockName;
		
		private string _StockUnit;
		
		private System.Nullable<decimal> _StockPurchasePrice;
		
		private System.Nullable<decimal> _StockSalePrice;
		
		private System.Nullable<decimal> _StockPurchaseTAX;
		
		private System.Nullable<decimal> _StockSaleTAX;
		
		private System.Nullable<int> _StockGroupID;
		
		private System.Data.Linq.Binary _StockPicture;
		
		private System.Nullable<int> _StockSaveUser;
		
		private System.Nullable<System.DateTime> _StockSaveDate;
		
		private System.Nullable<int> _StockEditUser;
		
		private System.Nullable<System.DateTime> _StockEditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnStockBarcodeChanging(string value);
    partial void OnStockBarcodeChanged();
    partial void OnStockCodeChanging(string value);
    partial void OnStockCodeChanged();
    partial void OnStockNameChanging(string value);
    partial void OnStockNameChanged();
    partial void OnStockUnitChanging(string value);
    partial void OnStockUnitChanged();
    partial void OnStockPurchasePriceChanging(System.Nullable<decimal> value);
    partial void OnStockPurchasePriceChanged();
    partial void OnStockSalePriceChanging(System.Nullable<decimal> value);
    partial void OnStockSalePriceChanged();
    partial void OnStockPurchaseTAXChanging(System.Nullable<decimal> value);
    partial void OnStockPurchaseTAXChanged();
    partial void OnStockSaleTAXChanging(System.Nullable<decimal> value);
    partial void OnStockSaleTAXChanged();
    partial void OnStockGroupIDChanging(System.Nullable<int> value);
    partial void OnStockGroupIDChanged();
    partial void OnStockPictureChanging(System.Data.Linq.Binary value);
    partial void OnStockPictureChanged();
    partial void OnStockSaveUserChanging(System.Nullable<int> value);
    partial void OnStockSaveUserChanged();
    partial void OnStockSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStockSaveDateChanged();
    partial void OnStockEditUserChanging(System.Nullable<int> value);
    partial void OnStockEditUserChanged();
    partial void OnStockEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStockEditDateChanged();
    #endregion
		
		public TBL_Stock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockBarcode", DbType="NVarChar(50)")]
		public string StockBarcode
		{
			get
			{
				return this._StockBarcode;
			}
			set
			{
				if ((this._StockBarcode != value))
				{
					this.OnStockBarcodeChanging(value);
					this.SendPropertyChanging();
					this._StockBarcode = value;
					this.SendPropertyChanged("StockBarcode");
					this.OnStockBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockCode", DbType="NVarChar(50)")]
		public string StockCode
		{
			get
			{
				return this._StockCode;
			}
			set
			{
				if ((this._StockCode != value))
				{
					this.OnStockCodeChanging(value);
					this.SendPropertyChanging();
					this._StockCode = value;
					this.SendPropertyChanged("StockCode");
					this.OnStockCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockName", DbType="NVarChar(50)")]
		public string StockName
		{
			get
			{
				return this._StockName;
			}
			set
			{
				if ((this._StockName != value))
				{
					this.OnStockNameChanging(value);
					this.SendPropertyChanging();
					this._StockName = value;
					this.SendPropertyChanged("StockName");
					this.OnStockNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockUnit", DbType="NVarChar(50)")]
		public string StockUnit
		{
			get
			{
				return this._StockUnit;
			}
			set
			{
				if ((this._StockUnit != value))
				{
					this.OnStockUnitChanging(value);
					this.SendPropertyChanging();
					this._StockUnit = value;
					this.SendPropertyChanged("StockUnit");
					this.OnStockUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockPurchasePrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> StockPurchasePrice
		{
			get
			{
				return this._StockPurchasePrice;
			}
			set
			{
				if ((this._StockPurchasePrice != value))
				{
					this.OnStockPurchasePriceChanging(value);
					this.SendPropertyChanging();
					this._StockPurchasePrice = value;
					this.SendPropertyChanged("StockPurchasePrice");
					this.OnStockPurchasePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockSalePrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> StockSalePrice
		{
			get
			{
				return this._StockSalePrice;
			}
			set
			{
				if ((this._StockSalePrice != value))
				{
					this.OnStockSalePriceChanging(value);
					this.SendPropertyChanging();
					this._StockSalePrice = value;
					this.SendPropertyChanged("StockSalePrice");
					this.OnStockSalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockPurchaseTAX", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> StockPurchaseTAX
		{
			get
			{
				return this._StockPurchaseTAX;
			}
			set
			{
				if ((this._StockPurchaseTAX != value))
				{
					this.OnStockPurchaseTAXChanging(value);
					this.SendPropertyChanging();
					this._StockPurchaseTAX = value;
					this.SendPropertyChanged("StockPurchaseTAX");
					this.OnStockPurchaseTAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockSaleTAX", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> StockSaleTAX
		{
			get
			{
				return this._StockSaleTAX;
			}
			set
			{
				if ((this._StockSaleTAX != value))
				{
					this.OnStockSaleTAXChanging(value);
					this.SendPropertyChanging();
					this._StockSaleTAX = value;
					this.SendPropertyChanged("StockSaleTAX");
					this.OnStockSaleTAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockGroupID", DbType="Int")]
		public System.Nullable<int> StockGroupID
		{
			get
			{
				return this._StockGroupID;
			}
			set
			{
				if ((this._StockGroupID != value))
				{
					this.OnStockGroupIDChanging(value);
					this.SendPropertyChanging();
					this._StockGroupID = value;
					this.SendPropertyChanged("StockGroupID");
					this.OnStockGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockPicture", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary StockPicture
		{
			get
			{
				return this._StockPicture;
			}
			set
			{
				if ((this._StockPicture != value))
				{
					this.OnStockPictureChanging(value);
					this.SendPropertyChanging();
					this._StockPicture = value;
					this.SendPropertyChanged("StockPicture");
					this.OnStockPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockSaveUser", DbType="Int")]
		public System.Nullable<int> StockSaveUser
		{
			get
			{
				return this._StockSaveUser;
			}
			set
			{
				if ((this._StockSaveUser != value))
				{
					this.OnStockSaveUserChanging(value);
					this.SendPropertyChanging();
					this._StockSaveUser = value;
					this.SendPropertyChanged("StockSaveUser");
					this.OnStockSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StockSaveDate
		{
			get
			{
				return this._StockSaveDate;
			}
			set
			{
				if ((this._StockSaveDate != value))
				{
					this.OnStockSaveDateChanging(value);
					this.SendPropertyChanging();
					this._StockSaveDate = value;
					this.SendPropertyChanged("StockSaveDate");
					this.OnStockSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockEditUser", DbType="Int")]
		public System.Nullable<int> StockEditUser
		{
			get
			{
				return this._StockEditUser;
			}
			set
			{
				if ((this._StockEditUser != value))
				{
					this.OnStockEditUserChanging(value);
					this.SendPropertyChanging();
					this._StockEditUser = value;
					this.SendPropertyChanged("StockEditUser");
					this.OnStockEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StockEditDate
		{
			get
			{
				return this._StockEditDate;
			}
			set
			{
				if ((this._StockEditDate != value))
				{
					this.OnStockEditDateChanging(value);
					this.SendPropertyChanging();
					this._StockEditDate = value;
					this.SendPropertyChanged("StockEditDate");
					this.OnStockEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_StockGroup")]
	public partial class TBL_StockGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GroupName;
		
		private string _GroupCode;
		
		private System.Nullable<int> _GroupSaveUser;
		
		private System.Nullable<System.DateTime> _GroupSaveDate;
		
		private System.Nullable<int> _GroupEditUser;
		
		private System.Nullable<System.DateTime> _GroupEditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    partial void OnGroupCodeChanging(string value);
    partial void OnGroupCodeChanged();
    partial void OnGroupSaveUserChanging(System.Nullable<int> value);
    partial void OnGroupSaveUserChanged();
    partial void OnGroupSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGroupSaveDateChanged();
    partial void OnGroupEditUserChanging(System.Nullable<int> value);
    partial void OnGroupEditUserChanged();
    partial void OnGroupEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGroupEditDateChanged();
    #endregion
		
		public TBL_StockGroup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(50)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="NVarChar(50)")]
		public string GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this.OnGroupCodeChanging(value);
					this.SendPropertyChanging();
					this._GroupCode = value;
					this.SendPropertyChanged("GroupCode");
					this.OnGroupCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupSaveUser", DbType="Int")]
		public System.Nullable<int> GroupSaveUser
		{
			get
			{
				return this._GroupSaveUser;
			}
			set
			{
				if ((this._GroupSaveUser != value))
				{
					this.OnGroupSaveUserChanging(value);
					this.SendPropertyChanging();
					this._GroupSaveUser = value;
					this.SendPropertyChanged("GroupSaveUser");
					this.OnGroupSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GroupSaveDate
		{
			get
			{
				return this._GroupSaveDate;
			}
			set
			{
				if ((this._GroupSaveDate != value))
				{
					this.OnGroupSaveDateChanging(value);
					this.SendPropertyChanging();
					this._GroupSaveDate = value;
					this.SendPropertyChanged("GroupSaveDate");
					this.OnGroupSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupEditUser", DbType="Int")]
		public System.Nullable<int> GroupEditUser
		{
			get
			{
				return this._GroupEditUser;
			}
			set
			{
				if ((this._GroupEditUser != value))
				{
					this.OnGroupEditUserChanging(value);
					this.SendPropertyChanging();
					this._GroupEditUser = value;
					this.SendPropertyChanged("GroupEditUser");
					this.OnGroupEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GroupEditDate
		{
			get
			{
				return this._GroupEditDate;
			}
			set
			{
				if ((this._GroupEditDate != value))
				{
					this.OnGroupEditDateChanging(value);
					this.SendPropertyChanging();
					this._GroupEditDate = value;
					this.SendPropertyChanged("GroupEditDate");
					this.OnGroupEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CurrentGroup")]
	public partial class TBL_CurrentGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CurrentGroupName;
		
		private string _CurrentGroupCode;
		
		private System.Nullable<System.DateTime> _CurrentGroupSaveDate;
		
		private System.Nullable<int> _CurrentGroupSaveUser;
		
		private System.Nullable<System.DateTime> _CurrentGroupEditDate;
		
		private System.Nullable<int> _CurrentGroupEditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCurrentGroupNameChanging(string value);
    partial void OnCurrentGroupNameChanged();
    partial void OnCurrentGroupCodeChanging(string value);
    partial void OnCurrentGroupCodeChanged();
    partial void OnCurrentGroupSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCurrentGroupSaveDateChanged();
    partial void OnCurrentGroupSaveUserChanging(System.Nullable<int> value);
    partial void OnCurrentGroupSaveUserChanged();
    partial void OnCurrentGroupEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCurrentGroupEditDateChanged();
    partial void OnCurrentGroupEditUserChanging(System.Nullable<int> value);
    partial void OnCurrentGroupEditUserChanged();
    #endregion
		
		public TBL_CurrentGroup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentGroupName", DbType="NVarChar(50)")]
		public string CurrentGroupName
		{
			get
			{
				return this._CurrentGroupName;
			}
			set
			{
				if ((this._CurrentGroupName != value))
				{
					this.OnCurrentGroupNameChanging(value);
					this.SendPropertyChanging();
					this._CurrentGroupName = value;
					this.SendPropertyChanged("CurrentGroupName");
					this.OnCurrentGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentGroupCode", DbType="NVarChar(50)")]
		public string CurrentGroupCode
		{
			get
			{
				return this._CurrentGroupCode;
			}
			set
			{
				if ((this._CurrentGroupCode != value))
				{
					this.OnCurrentGroupCodeChanging(value);
					this.SendPropertyChanging();
					this._CurrentGroupCode = value;
					this.SendPropertyChanged("CurrentGroupCode");
					this.OnCurrentGroupCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentGroupSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CurrentGroupSaveDate
		{
			get
			{
				return this._CurrentGroupSaveDate;
			}
			set
			{
				if ((this._CurrentGroupSaveDate != value))
				{
					this.OnCurrentGroupSaveDateChanging(value);
					this.SendPropertyChanging();
					this._CurrentGroupSaveDate = value;
					this.SendPropertyChanged("CurrentGroupSaveDate");
					this.OnCurrentGroupSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentGroupSaveUser", DbType="Int")]
		public System.Nullable<int> CurrentGroupSaveUser
		{
			get
			{
				return this._CurrentGroupSaveUser;
			}
			set
			{
				if ((this._CurrentGroupSaveUser != value))
				{
					this.OnCurrentGroupSaveUserChanging(value);
					this.SendPropertyChanging();
					this._CurrentGroupSaveUser = value;
					this.SendPropertyChanged("CurrentGroupSaveUser");
					this.OnCurrentGroupSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentGroupEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CurrentGroupEditDate
		{
			get
			{
				return this._CurrentGroupEditDate;
			}
			set
			{
				if ((this._CurrentGroupEditDate != value))
				{
					this.OnCurrentGroupEditDateChanging(value);
					this.SendPropertyChanging();
					this._CurrentGroupEditDate = value;
					this.SendPropertyChanged("CurrentGroupEditDate");
					this.OnCurrentGroupEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentGroupEditUser", DbType="Int")]
		public System.Nullable<int> CurrentGroupEditUser
		{
			get
			{
				return this._CurrentGroupEditUser;
			}
			set
			{
				if ((this._CurrentGroupEditUser != value))
				{
					this.OnCurrentGroupEditUserChanging(value);
					this.SendPropertyChanging();
					this._CurrentGroupEditUser = value;
					this.SendPropertyChanged("CurrentGroupEditUser");
					this.OnCurrentGroupEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Current")]
	public partial class TBL_Current : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CurrentCode;
		
		private string _CurrentName;
		
		private string _CurrentTaxOffice;
		
		private string _CurrentTaxNumber;
		
		private System.Nullable<int> _CurrentGroupID;
		
		private string _CurrentCountry;
		
		private string _CurrentCity;
		
		private string _CurrentDistrict;
		
		private string _CurrentAddress;
		
		private string _CurrentPhone1;
		
		private string _CurrentPhone2;
		
		private string _CurrentFax1;
		
		private string _CurrentFax2;
		
		private string _CurrentWebAddress;
		
		private string _CurrentMailInfo;
		
		private string _CurrentAuthorized1;
		
		private string _CurrentAuthorized1Mail;
		
		private string _CurrentAuthorized2;
		
		private string _CurrentAuthorized2Mail;
		
		private System.Nullable<System.DateTime> _CurrentSaveDate;
		
		private System.Nullable<int> _CurrentSaveUser;
		
		private System.Nullable<System.DateTime> _CurrentEditDate;
		
		private System.Nullable<int> _CurrentEditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCurrentCodeChanging(string value);
    partial void OnCurrentCodeChanged();
    partial void OnCurrentNameChanging(string value);
    partial void OnCurrentNameChanged();
    partial void OnCurrentTaxOfficeChanging(string value);
    partial void OnCurrentTaxOfficeChanged();
    partial void OnCurrentTaxNumberChanging(string value);
    partial void OnCurrentTaxNumberChanged();
    partial void OnCurrentGroupIDChanging(System.Nullable<int> value);
    partial void OnCurrentGroupIDChanged();
    partial void OnCurrentCountryChanging(string value);
    partial void OnCurrentCountryChanged();
    partial void OnCurrentCityChanging(string value);
    partial void OnCurrentCityChanged();
    partial void OnCurrentDistrictChanging(string value);
    partial void OnCurrentDistrictChanged();
    partial void OnCurrentAddressChanging(string value);
    partial void OnCurrentAddressChanged();
    partial void OnCurrentPhone1Changing(string value);
    partial void OnCurrentPhone1Changed();
    partial void OnCurrentPhone2Changing(string value);
    partial void OnCurrentPhone2Changed();
    partial void OnCurrentFax1Changing(string value);
    partial void OnCurrentFax1Changed();
    partial void OnCurrentFax2Changing(string value);
    partial void OnCurrentFax2Changed();
    partial void OnCurrentWebAddressChanging(string value);
    partial void OnCurrentWebAddressChanged();
    partial void OnCurrentMailInfoChanging(string value);
    partial void OnCurrentMailInfoChanged();
    partial void OnCurrentAuthorized1Changing(string value);
    partial void OnCurrentAuthorized1Changed();
    partial void OnCurrentAuthorized1MailChanging(string value);
    partial void OnCurrentAuthorized1MailChanged();
    partial void OnCurrentAuthorized2Changing(string value);
    partial void OnCurrentAuthorized2Changed();
    partial void OnCurrentAuthorized2MailChanging(string value);
    partial void OnCurrentAuthorized2MailChanged();
    partial void OnCurrentSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCurrentSaveDateChanged();
    partial void OnCurrentSaveUserChanging(System.Nullable<int> value);
    partial void OnCurrentSaveUserChanged();
    partial void OnCurrentEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCurrentEditDateChanged();
    partial void OnCurrentEditUserChanging(System.Nullable<int> value);
    partial void OnCurrentEditUserChanged();
    #endregion
		
		public TBL_Current()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentCode", DbType="NVarChar(50)")]
		public string CurrentCode
		{
			get
			{
				return this._CurrentCode;
			}
			set
			{
				if ((this._CurrentCode != value))
				{
					this.OnCurrentCodeChanging(value);
					this.SendPropertyChanging();
					this._CurrentCode = value;
					this.SendPropertyChanged("CurrentCode");
					this.OnCurrentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentName", DbType="NVarChar(50)")]
		public string CurrentName
		{
			get
			{
				return this._CurrentName;
			}
			set
			{
				if ((this._CurrentName != value))
				{
					this.OnCurrentNameChanging(value);
					this.SendPropertyChanging();
					this._CurrentName = value;
					this.SendPropertyChanged("CurrentName");
					this.OnCurrentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentTaxOffice", DbType="NVarChar(50)")]
		public string CurrentTaxOffice
		{
			get
			{
				return this._CurrentTaxOffice;
			}
			set
			{
				if ((this._CurrentTaxOffice != value))
				{
					this.OnCurrentTaxOfficeChanging(value);
					this.SendPropertyChanging();
					this._CurrentTaxOffice = value;
					this.SendPropertyChanged("CurrentTaxOffice");
					this.OnCurrentTaxOfficeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentTaxNumber", DbType="NVarChar(20)")]
		public string CurrentTaxNumber
		{
			get
			{
				return this._CurrentTaxNumber;
			}
			set
			{
				if ((this._CurrentTaxNumber != value))
				{
					this.OnCurrentTaxNumberChanging(value);
					this.SendPropertyChanging();
					this._CurrentTaxNumber = value;
					this.SendPropertyChanged("CurrentTaxNumber");
					this.OnCurrentTaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentGroupID", DbType="Int")]
		public System.Nullable<int> CurrentGroupID
		{
			get
			{
				return this._CurrentGroupID;
			}
			set
			{
				if ((this._CurrentGroupID != value))
				{
					this.OnCurrentGroupIDChanging(value);
					this.SendPropertyChanging();
					this._CurrentGroupID = value;
					this.SendPropertyChanged("CurrentGroupID");
					this.OnCurrentGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentCountry", DbType="NVarChar(50)")]
		public string CurrentCountry
		{
			get
			{
				return this._CurrentCountry;
			}
			set
			{
				if ((this._CurrentCountry != value))
				{
					this.OnCurrentCountryChanging(value);
					this.SendPropertyChanging();
					this._CurrentCountry = value;
					this.SendPropertyChanged("CurrentCountry");
					this.OnCurrentCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentCity", DbType="NVarChar(50)")]
		public string CurrentCity
		{
			get
			{
				return this._CurrentCity;
			}
			set
			{
				if ((this._CurrentCity != value))
				{
					this.OnCurrentCityChanging(value);
					this.SendPropertyChanging();
					this._CurrentCity = value;
					this.SendPropertyChanged("CurrentCity");
					this.OnCurrentCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentDistrict", DbType="NVarChar(50)")]
		public string CurrentDistrict
		{
			get
			{
				return this._CurrentDistrict;
			}
			set
			{
				if ((this._CurrentDistrict != value))
				{
					this.OnCurrentDistrictChanging(value);
					this.SendPropertyChanging();
					this._CurrentDistrict = value;
					this.SendPropertyChanged("CurrentDistrict");
					this.OnCurrentDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentAddress", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string CurrentAddress
		{
			get
			{
				return this._CurrentAddress;
			}
			set
			{
				if ((this._CurrentAddress != value))
				{
					this.OnCurrentAddressChanging(value);
					this.SendPropertyChanging();
					this._CurrentAddress = value;
					this.SendPropertyChanged("CurrentAddress");
					this.OnCurrentAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentPhone1", DbType="NVarChar(16)")]
		public string CurrentPhone1
		{
			get
			{
				return this._CurrentPhone1;
			}
			set
			{
				if ((this._CurrentPhone1 != value))
				{
					this.OnCurrentPhone1Changing(value);
					this.SendPropertyChanging();
					this._CurrentPhone1 = value;
					this.SendPropertyChanged("CurrentPhone1");
					this.OnCurrentPhone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentPhone2", DbType="NChar(10)")]
		public string CurrentPhone2
		{
			get
			{
				return this._CurrentPhone2;
			}
			set
			{
				if ((this._CurrentPhone2 != value))
				{
					this.OnCurrentPhone2Changing(value);
					this.SendPropertyChanging();
					this._CurrentPhone2 = value;
					this.SendPropertyChanged("CurrentPhone2");
					this.OnCurrentPhone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentFax1", DbType="NChar(10)")]
		public string CurrentFax1
		{
			get
			{
				return this._CurrentFax1;
			}
			set
			{
				if ((this._CurrentFax1 != value))
				{
					this.OnCurrentFax1Changing(value);
					this.SendPropertyChanging();
					this._CurrentFax1 = value;
					this.SendPropertyChanged("CurrentFax1");
					this.OnCurrentFax1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentFax2", DbType="NVarChar(16)")]
		public string CurrentFax2
		{
			get
			{
				return this._CurrentFax2;
			}
			set
			{
				if ((this._CurrentFax2 != value))
				{
					this.OnCurrentFax2Changing(value);
					this.SendPropertyChanging();
					this._CurrentFax2 = value;
					this.SendPropertyChanged("CurrentFax2");
					this.OnCurrentFax2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentWebAddress", DbType="NVarChar(150)")]
		public string CurrentWebAddress
		{
			get
			{
				return this._CurrentWebAddress;
			}
			set
			{
				if ((this._CurrentWebAddress != value))
				{
					this.OnCurrentWebAddressChanging(value);
					this.SendPropertyChanging();
					this._CurrentWebAddress = value;
					this.SendPropertyChanged("CurrentWebAddress");
					this.OnCurrentWebAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentMailInfo", DbType="NVarChar(250)")]
		public string CurrentMailInfo
		{
			get
			{
				return this._CurrentMailInfo;
			}
			set
			{
				if ((this._CurrentMailInfo != value))
				{
					this.OnCurrentMailInfoChanging(value);
					this.SendPropertyChanging();
					this._CurrentMailInfo = value;
					this.SendPropertyChanged("CurrentMailInfo");
					this.OnCurrentMailInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentAuthorized1", DbType="NVarChar(50)")]
		public string CurrentAuthorized1
		{
			get
			{
				return this._CurrentAuthorized1;
			}
			set
			{
				if ((this._CurrentAuthorized1 != value))
				{
					this.OnCurrentAuthorized1Changing(value);
					this.SendPropertyChanging();
					this._CurrentAuthorized1 = value;
					this.SendPropertyChanged("CurrentAuthorized1");
					this.OnCurrentAuthorized1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentAuthorized1Mail", DbType="NVarChar(250)")]
		public string CurrentAuthorized1Mail
		{
			get
			{
				return this._CurrentAuthorized1Mail;
			}
			set
			{
				if ((this._CurrentAuthorized1Mail != value))
				{
					this.OnCurrentAuthorized1MailChanging(value);
					this.SendPropertyChanging();
					this._CurrentAuthorized1Mail = value;
					this.SendPropertyChanged("CurrentAuthorized1Mail");
					this.OnCurrentAuthorized1MailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentAuthorized2", DbType="NVarChar(50)")]
		public string CurrentAuthorized2
		{
			get
			{
				return this._CurrentAuthorized2;
			}
			set
			{
				if ((this._CurrentAuthorized2 != value))
				{
					this.OnCurrentAuthorized2Changing(value);
					this.SendPropertyChanging();
					this._CurrentAuthorized2 = value;
					this.SendPropertyChanged("CurrentAuthorized2");
					this.OnCurrentAuthorized2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentAuthorized2Mail", DbType="NVarChar(250)")]
		public string CurrentAuthorized2Mail
		{
			get
			{
				return this._CurrentAuthorized2Mail;
			}
			set
			{
				if ((this._CurrentAuthorized2Mail != value))
				{
					this.OnCurrentAuthorized2MailChanging(value);
					this.SendPropertyChanging();
					this._CurrentAuthorized2Mail = value;
					this.SendPropertyChanged("CurrentAuthorized2Mail");
					this.OnCurrentAuthorized2MailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CurrentSaveDate
		{
			get
			{
				return this._CurrentSaveDate;
			}
			set
			{
				if ((this._CurrentSaveDate != value))
				{
					this.OnCurrentSaveDateChanging(value);
					this.SendPropertyChanging();
					this._CurrentSaveDate = value;
					this.SendPropertyChanged("CurrentSaveDate");
					this.OnCurrentSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentSaveUser", DbType="Int")]
		public System.Nullable<int> CurrentSaveUser
		{
			get
			{
				return this._CurrentSaveUser;
			}
			set
			{
				if ((this._CurrentSaveUser != value))
				{
					this.OnCurrentSaveUserChanging(value);
					this.SendPropertyChanging();
					this._CurrentSaveUser = value;
					this.SendPropertyChanged("CurrentSaveUser");
					this.OnCurrentSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CurrentEditDate
		{
			get
			{
				return this._CurrentEditDate;
			}
			set
			{
				if ((this._CurrentEditDate != value))
				{
					this.OnCurrentEditDateChanging(value);
					this.SendPropertyChanging();
					this._CurrentEditDate = value;
					this.SendPropertyChanged("CurrentEditDate");
					this.OnCurrentEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentEditUser", DbType="Int")]
		public System.Nullable<int> CurrentEditUser
		{
			get
			{
				return this._CurrentEditUser;
			}
			set
			{
				if ((this._CurrentEditUser != value))
				{
					this.OnCurrentEditUserChanging(value);
					this.SendPropertyChanging();
					this._CurrentEditUser = value;
					this.SendPropertyChanged("CurrentEditUser");
					this.OnCurrentEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
