<?xml version="1.0" encoding="utf-8"?><Database Name="PreAccountancy" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-83SGN10\SQLEXPRESS;Initial Catalog=PreAccountancy;Integrated Security=True" SettingsObjectName="PreAccountancy.Properties.Settings" SettingsPropertyName="PreAccountancyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_Stock" Member="TBL_Stocks">
    <Type Name="TBL_Stock">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StockBarcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StockCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StockName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StockUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StockPurchasePrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StockSalePrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StockPurchaseTAX" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StockSaleTAX" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StockGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockPicture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StockSaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockSaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StockEditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_StockGroup" Member="TBL_StockGroups">
    <Type Name="TBL_StockGroup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupSaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupSaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GroupEditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>